if(NOT WIN32)
    message(FATAL_ERROR "The msys2-ucrt64 toolchain file is intended for Windows hosts.")
endif()

if(DEFINED ENV{MSYSTEM_PREFIX} AND NOT "$ENV{MSYSTEM_PREFIX}" STREQUAL "")
    set(_msys2_prefix "$ENV{MSYSTEM_PREFIX}")
elseif(DEFINED ENV{MINGW_PREFIX} AND NOT "$ENV{MINGW_PREFIX}" STREQUAL "")
    set(_msys2_prefix "$ENV{MINGW_PREFIX}")
else()
    message(FATAL_ERROR "MSYS2 UCRT64 was not detected. Open a UCRT64 shell and try again.")
endif()

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_C_COMPILER "${_msys2_prefix}/bin/gcc.exe" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${_msys2_prefix}/bin/g++.exe" CACHE FILEPATH "" FORCE)
set(CMAKE_RC_COMPILER "${_msys2_prefix}/bin/windres.exe" CACHE FILEPATH "" FORCE)
set(CMAKE_AR "${_msys2_prefix}/bin/ar.exe" CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB "${_msys2_prefix}/bin/ranlib.exe" CACHE FILEPATH "" FORCE)

set(CMAKE_FIND_ROOT_PATH "${_msys2_prefix}" CACHE PATH "" FORCE)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
